name: Overall CI
# targeting pull requests to master branch
on:
  workflow_call:
  pull_request:
    branches: [master]
  push:
    branches: [master]
permissions:
  checks: write
  pull-requests: write
  contents: write
  actions: read 
  id-token: write
jobs:
    frontend_ci:
        uses: ./.github/workflows/frontend_CI.yml
    backend_ci:
        uses: ./.github/workflows/Backend_CI.yml
    deploy_production:
        name: Deploy Production
        needs: [frontend_ci, backend_ci]      
        if: github.repository == 'CS3213-Frontend-Management-System/master' && github.ref_type == 'tag'
        uses: ./.github/workflows/CD_to_AKS.yml
